### ISSUE TITLE
Customer places an order

### ISSUE THREAD

**Issue by Jathoosh** [RomainMarques/OrderSharing#4]
**Domain : Order Management**

The order of each unique customer (Individual Order) will be added to a global order (Shared Older) with all other orders of the bowling alley.

The global order must be confirmed at the end to process to the payment part. RomainMarques/OrderSharing#8 

Containing : 
- content in the global basket, 
- the Park Id 
- and the Alley number

Before sending the order, the customer must confirm : 
-  his name, 
- email address
- and phone number (optional)

**Comment by anto-lcd** [comment]
Ca résume à insérer un order dans la base de données

**Comment by anto-lcd** [comment]
Almost done. Need to do :  
- positive ID of individualOrder
- Add checks where comment is
